Shader "Custom/NewSurfaceShader"

8: mov o1.xy, v1.xyxx
9 : ret
// Approximately 0 instruction slots used


-- Hardware tier variant : Tier 1
--Fragment shader for "d3d11" :
	// Stats: 10 math, 2 temp registers, 2 textures
	Set 2D Texture "_RayCast" to slot 0 sampler slot 1
	Set 2D Texture "_MainTex" to slot 1 sampler slot 0

	Constant Buffer "$Globals" (560 bytes) on slot 0 {
	Float _EdgeFactor at 144
}

Shader Disassembly :
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[10], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d(float, float, float, float) t0
dcl_resource_texture2d(float, float, float, float) t1
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 2
0: sample r0.xyzw, v1.xyxx, t0.xyzw, s1
1 : max r0.z, r0.y, r0.x
2 : add r0.z, -r0.z, l(1.000000)
3 : min r1.x, r0.y, r0.x
4 : min r0.z, r0.z, r1.x
5 : lt r1.x, cb0[9].x, r0.z
6 : div_sat r0.z, r0.z, cb0[9].x
7 : movc r0.z, r1.x, l(1.000000), r0.z
8 : mul o0.w, r0.z, r0.w
9 : sample r0.xyzw, r0.xyxx, t1.xyzw, s0
10 : dp3 r0.w, r0.xyzx, l(0.220000, 0.707000, 0.071000, 0.000000)
11 : add r0.w, r0.w, l(1.000000)
12 : div o0.xyz, r0.xyzx, r0.wwww
13 : ret
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 8 math
 // Stats for Fragment shader:
 //        d3d11: 51 math, 4 texture
 Pass{
  ZTest Always
  ZWrite Off
  Cull Off
	 //////////////////////////////////
	 //                              //
	 //      Compiled programs       //
	 //                              //
	 //////////////////////////////////
   //////////////////////////////////////////////////////
   Global Keywords : <none>
   Local Keywords : <none>
   --Hardware tier variant : Tier 1
   --Vertex shader for "d3d11" :
	 // Stats: 8 math, 2 temp registers
	 Uses vertex data channel "Vertex"
	 Uses vertex data channel "TexCoord0"

	 Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
	   Matrix4x4 unity_ObjectToWorld at 0
	 }
	 Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
	   Matrix4x4 unity_MatrixVP at 272
	 }

	 Shader Disassembly :
	 //
	 // Generated by Microsoft (R) D3D Shader Disassembler
	 //
	 //
	 // Input signature:
	 //
	 // Name                 Index   Mask Register SysValue  Format   Used
	 // -------------------- ----- ------ -------- -------- ------- ------
	 // POSITION                 0   xyzw        0     NONE   float   xyz 
	 // TEXCOORD                 0   xy          1     NONE   float   xy  
	 //
	 //
	 // Output signature:
	 //
	 // Name                 Index   Mask Register SysValue  Format   Used
	 // -------------------- ----- ------ -------- -------- ------- ------
	 // SV_Position              0   xyzw        0      POS   float   xyzw
	 // TEXCOORD                 0   xy          1     NONE   float   xy  
	 //
		   vs_4_0
		   dcl_constantbuffer CB0[4], immediateIndexed
		   dcl_constantbuffer CB1[21], immediateIndexed
		   dcl_input v0.xyz
		   dcl_input v1.xy
		   dcl_output_siv o0.xyzw, position
		   dcl_output o1.xy
		   dcl_temps 2
		0: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
		1 : mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
		2 : mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
		3 : add r0.xyzw, r0.xyzw, cb0[3].xyzw
		4 : mul r1.xyzw, r0.yyyy, cb1[18].xyzw
		5 : mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
		6 : mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
		7 : mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
		8 : mov o1.xy, v1.xyxx
		9 : ret
			   // Approximately 0 instruction slots used


			   -- Hardware tier variant : Tier 1
			   --Fragment shader for "d3d11" :
			   // Stats: 51 math, 5 temp registers, 4 textures
			   Set 2D Texture "_CameraDepthTexture" to slot 0 sampler slot 5
			   Set 2D Texture "_CameraReflectionsTexture" to slot 1 sampler slot 4
			   Set 2D Texture "_CameraGBufferTexture2" to slot 2 sampler slot 3
			   Set 2D Texture "_CameraGBufferTexture1" to slot 3 sampler slot 2
			   Set 2D Texture "_ReflectionBuffer" to slot 4 sampler slot 1
			   Set 2D Texture "_MainTex" to slot 5 sampler slot 0

			   Constant Buffer "$Globals" (560 bytes) on slot 0 {
				 Matrix4x4 _InverseViewProjectionMatrix at 352
				 Float _SmoothnessRange at 148
			   }
			   Constant Buffer "UnityPerCamera" (144 bytes) on slot 1 {
				 Vector3 _WorldSpaceCameraPos at 64
			   }

			   Shader Disassembly :
			   //
			   // Generated by Microsoft (R) D3D Shader Disassembler
			   //
			   //
			   // Input signature:
			   //
			   // Name                 Index   Mask Register SysValue  Format   Used
			   // -------------------- ----- ------ -------- -------- ------- ------
			   // SV_Position              0   xyzw        0      POS   float       
			   // TEXCOORD                 0   xy          1     NONE   float   xy  
			   //
			   //
			   // Output signature:
			   //
			   // Name                 Index   Mask Register SysValue  Format   Used
			   // -------------------- ----- ------ -------- -------- ------- ------
			   // SV_Target                0   xyzw        0   TARGET   float   xyzw
			   //
					 ps_4_0
					 dcl_constantbuffer CB0[26], immediateIndexed
					 dcl_constantbuffer CB1[5], immediateIndexed
					 dcl_sampler s0, mode_default
					 dcl_sampler s1, mode_default
					 dcl_sampler s2, mode_default
					 dcl_sampler s3, mode_default
					 dcl_sampler s4, mode_default
					 dcl_sampler s5, mode_default
					 dcl_resource_texture2d(float,float,float,float) t0
					 dcl_resource_texture2d(float,float,float,float) t1
					 dcl_resource_texture2d(float,float,float,float) t2
					 dcl_resource_texture2d(float,float,float,float) t3
					 dcl_resource_texture2d(float,float,float,float) t4
					 dcl_resource_texture2d(float,float,float,float) t5
					 dcl_input_ps linear v1.xy
					 dcl_output o0.xyzw
					 dcl_temps 5
				  0: mad r0.xy, v1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
				  1 : mul r1.xyzw, r0.yyyy, cb0[23].xyzw
				  2 : mad r0.xyzw, cb0[22].xyzw, r0.xxxx, r1.xyzw
				  3 : sample_l r1.xyzw, v1.xyxx, t0.xyzw, s5, l(0.000000)
				  4 : mad r0.xyzw, cb0[24].xyzw, r1.xxxx, r0.xyzw
				  5 : add r0.xyzw, r0.xyzw, cb0[25].xyzw
				  6 : div r0.xyz, r0.xyzx, r0.wwww
				  7 : add r0.xyz, r0.xyzx, -cb1[4].xyzx
				  8 : dp3 r0.w, r0.xyzx, r0.xyzx
				  9 : rsq r0.w, r0.w
				 10 : mul r0.xyz, r0.wwww, r0.xyzx
				 11 : sample r1.xyzw, v1.xyxx, t2.xyzw, s3
				 12 : mad r1.xyz, r1.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
				 13 : dp3 r0.w, -r0.xyzx, r1.xyzx
				 14 : add r1.w, -| r0.w | , l(1.000000)
				 15 : add r0.w, r0.w, r0.w
				 16 : mad r1.xyz, r1.xyzx, -r0.wwww, -r0.xyzx
				 17 : mul r0.w, r1.w, r1.w
				 18 : mul r0.w, r0.w, r0.w
				 19 : mul r0.w, r1.w, r0.w
				 20 : sample r2.xyzw, v1.xyxx, t3.xyzw, s2
				 21 : max r1.w, r2.y, r2.x
				 22 : max r1.w, r2.z, r1.w
				 23 : add r1.w, -r1.w, l(1.000000)
				 24 : add r3.x, -cb0[9].y, l(1.000000)
				 25 : max r2.w, r2.w, r3.x
				 26 : max r2.w, r2.w, l(0.050000)
				 27 : add r1.w, -r1.w, r2.w
				 28 : add r2.w, -r2.w, l(1.000000)
				 29 : add_sat r1.w, r1.w, l(1.000000)
				 30 : add r3.xyz, -r2.xyzx, r1.wwww
				 31 : mad r2.xyz, r0.wwww, r3.xyzx, r2.xyzx
				 32 : mul r0.w, r2.w, r2.w
				 33 : max r0.w, r0.w, l(0.002000)
				 34 : mul r0.w, r0.w, r2.w
				 35 : mul r1.w, r2.w, l(10.000000)
				 36 : max r1.w, r1.w, l(0.000000)
				 37 : min r1.w, r1.w, l(4.000000)
				 38 : sample_l r3.xyzw, v1.xyxx, t4.xyzw, s1, r1.w
				 39 : mad r0.w, -r0.w, l(0.280000), l(1.000000)
				 40 : dp3 r1.w, r3.xyzx, l(0.220000, 0.707000, 0.071000, 0.000000)
				 41 : add r1.w, -r1.w, l(1.000000)
				 42 : div r3.xyz, r3.xyzx, r1.wwww
				 43 : mul r3.xyz, r0.wwww, r3.xyzx
				 44 : sample r4.xyzw, v1.xyxx, t1.xyzw, s4
				 45 : mad r2.xyz, r3.xyzx, r2.xyzx, -r4.xyzx
				 46 : dp3 r0.w, r1.xyzx, r1.xyzx
				 47 : rsq r0.w, r0.w
				 48 : mul r1.xyz, r0.wwww, r1.xyzx
				 49 : dp3 r0.x, -r0.xyzx, r1.xyzx
				 50 : add_sat r0.x, r0.x, r0.x
				 51 : mul r0.x, r0.x, r3.w
				 52 : mad r0.xyz, r0.xxxx, r2.xyzx, r4.xyzx
				 53 : sample r1.xyzw, v1.xyxx, t5.xyzw, s0
				 54 : add r1.xyz, -r4.xyzx, r1.xyzx
				 55 : mov o0.w, r1.w
				 56 : max r1.xyz, r1.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
				 57 : add o0.xyz, r0.xyzx, r1.xyzx
				 58 : ret
						 // Approximately 0 instruction slots used


 }


	 // Stats for Vertex shader:
	 //        d3d11: 8 math
	 // Stats for Fragment shader:
	 //        d3d11: 1 math
						 Pass{
						  ZTest Always
						  ZWrite Off
						  Cull Off
						 //////////////////////////////////
						 //                              //
						 //      Compiled programs       //
						 //                              //
						 //////////////////////////////////
					   //////////////////////////////////////////////////////
					   Global Keywords : <none>
					   Local Keywords : <none>
					   --Hardware tier variant : Tier 1
					   --Vertex shader for "d3d11" :
						 // Stats: 8 math, 2 temp registers
						 Uses vertex data channel "Vertex"
						 Uses vertex data channel "TexCoord0"

						 Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
						   Matrix4x4 unity_ObjectToWorld at 0
						 }
						 Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
						   Matrix4x4 unity_MatrixVP at 272
						 }

						 Shader Disassembly :
						 //
						 // Generated by Microsoft (R) D3D Shader Disassembler
						 //
						 //
						 // Input signature:
						 //
						 // Name                 Index   Mask Register SysValue  Format   Used
						 // -------------------- ----- ------ -------- -------- ------- ------
						 // POSITION                 0   xyzw        0     NONE   float   xyz 
						 // TEXCOORD                 0   xy          1     NONE   float   xy  
						 //
						 //
						 // Output signature:
						 //
						 // Name                 Index   Mask Register SysValue  Format   Used
						 // -------------------- ----- ------ -------- -------- ------- ------
						 // SV_Position              0   xyzw        0      POS   float   xyzw
						 // TEXCOORD                 0   xy          1     NONE   float   xy  
						 //
							   vs_4_0
							   dcl_constantbuffer CB0[4], immediateIndexed
							   dcl_constantbuffer CB1[21], immediateIndexed
							   dcl_input v0.xyz
							   dcl_input v1.xy
							   dcl_output_siv o0.xyzw, position
							   dcl_output o1.xy
							   dcl_temps 2
							0: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
							1 : mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
							2 : mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
							3 : add r0.xyzw, r0.xyzw, cb0[3].xyzw
							4 : mul r1.xyzw, r0.yyyy, cb1[18].xyzw
							5 : mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
							6 : mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
							7 : mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
							8 : mov o1.xy, v1.xyxx
							9 : ret
								   // Approximately 0 instruction slots used


								   -- Hardware tier variant : Tier 1
								   --Fragment shader for "d3d11" :
								   // Stats: 1 math, 1 temp registers
								   Set 2D Texture "_MipMapBuffer" to slot 0

								   Shader Disassembly :
							   //
							   // Generated by Microsoft (R) D3D Shader Disassembler
							   //
							   //
							   // Input signature:
							   //
							   // Name                 Index   Mask Register SysValue  Format   Used
							   // -------------------- ----- ------ -------- -------- ------- ------
							   // SV_Position              0   xyzw        0      POS   float       
							   // TEXCOORD                 0   xy          1     NONE   float   xy  
							   //
							   //
							   // Output signature:
							   //
							   // Name                 Index   Mask Register SysValue  Format   Used
							   // -------------------- ----- ------ -------- -------- ------- ------
							   // SV_Target                0   xyzw        0   TARGET   float   xyzw
							   //
									 ps_4_0
									 dcl_sampler s0, mode_default
									 dcl_resource_texture2d(float,float,float,float) t0
									 dcl_input_ps linear v1.xy
									 dcl_output o0.xyzw
									 dcl_temps 1
								  0: mul r0.x, v1.x, l(4.000000)
								  1 : sample_l o0.xyzw, v1.xyxx, t0.xyzw, s0, r0.x
								  2 : ret
										 // Approximately 0 instruction slots used


					 }
}
FallBack "Diffuse"
}
