//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class SkillSetting :  Bright.Config.BeanBase 
{
    public SkillSetting(JSONNode _json) 
    {
        { if(!_json["id"].IsString) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        { if(!_json["sound"].IsNumber) { throw new SerializationException(); }  Sound = _json["sound"]; }
        { if(!_json["forceVec3"].IsObject) { throw new SerializationException(); }  ForceVec3 = Vec3.DeserializeVec3(_json["forceVec3"]); }
        PostInit();
    }

    public SkillSetting(string id, string name, string desc, int sound, Vec3 forceVec3 ) 
    {
        this.Id = id;
        this.Name = name;
        this.Desc = desc;
        this.Sound = sound;
        this.ForceVec3 = forceVec3;
        PostInit();
    }

    public static SkillSetting DeserializeSkillSetting(JSONNode _json)
    {
        return new SkillSetting(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 音效
    /// </summary>
    public int Sound { get; private set; }
    /// <summary>
    /// 推力
    /// </summary>
    public Vec3 ForceVec3 { get; private set; }

    public const int __ID__ = 633610975;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        ForceVec3?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        ForceVec3?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Sound:" + Sound + ","
        + "ForceVec3:" + ForceVec3 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
