//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class SkillSettingReader
{
    private readonly Dictionary<string, SkillSetting> _dataMap;
    private readonly List<SkillSetting> _dataList;
    
    public SkillSettingReader(JSONNode _json)
    {
        _dataMap = new Dictionary<string, SkillSetting>();
        _dataList = new List<SkillSetting>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = SkillSetting.DeserializeSkillSetting(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, SkillSetting> DataMap => _dataMap;
    public List<SkillSetting> DataList => _dataList;

    public SkillSetting GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillSetting Get(string key) => _dataMap[key];
    public SkillSetting this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}